#!/bin/bash
#SBATCH -t 48:00:00
#SBATCH -p shen
#SBATCH --cpus-per-task=64
#SBATCH --job-name=simulate_benchmarking_data

source /home/ayush.semwal/.bashrc

mamba activate python_3_10_12

cd /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/

# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/concat_2x gencode.v44.transcripts.fa --invalid-type concat_2x --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/concat_2x.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/concat_3x gencode.v44.transcripts.fa --invalid-type concat_3x --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/concat_5x.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/concat_2x_rev gencode.v44.transcripts.fa --invalid-type concat_2x_rev --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/concat_2x_rev.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/concat_2x_rev_comp gencode.v44.transcripts.fa --invalid-type concat_2x_revcomp --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/concat_2x_rev_comp.log 2>&1
( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/fwd_rev_fwd gencode.v44.transcripts.fa --invalid-type fwd_rev_fwd --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/fwd_rev_fwd.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/fwd_rev_rev gencode.v44.transcripts.fa --invalid-type fwd_rev_rev --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/fwd_rev_rev.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/fwd_fwd_rev gencode.v44.transcripts.fa --invalid-type fwd_fwd_rev --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/fwd_fwd_rev.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/rev_rev_fwd gencode.v44.transcripts.fa --invalid-type rev_rev_fwd --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/rev_rev_fwd.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/rev_fwd_fwd gencode.v44.transcripts.fa --invalid-type rev_fwd_fwd --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/rev_fwd_fwd.log 2>&1
( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/rev_fwd_rev gencode.v44.transcripts.fa --invalid-type rev_fwd_rev --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/rev_fwd_rev.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/5p_repeat gencode.v44.transcripts.fa --invalid-type 5p_repeat --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/5p_repeat.log 2>&1
# ( time python3 invalid_reads.py 10x3p_sc /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/invalid_reads/3p_repeat gencode.v44.transcripts.fa --invalid-type 3p_repeat --cbc-whitelist-domain /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/3M-february-2018.txt --num-reads 100000 --threads 64  ) > /varidata/research/projects/shen/projects/2024_05_02_LRAnnot/simulate_benchmarking_data/3p_repeat.log 2>&1
